pluginManagement {
    // 版本号统一来自根 gradle.properties。
    def buildProperties = new Properties()
    file('gradle.properties').withInputStream { buildProperties.load(it) }

    plugins {
        id 'net.neoforged.moddev' version buildProperties.getProperty('moddev_version')
        id 'org.gradle.toolchains.foojay-resolver-convention' version buildProperties.getProperty('foojay_resolver_version')
    }

    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url = 'https://maven.parchmentmc.org' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention'
}
