buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        maven { url = 'https://maven.parchmentmc.org' }
        mavenCentral()
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
    id 'scala'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'maven-publish'
}

apply plugin: 'org.spongepowered.mixin'

group = mod_group_id

def buildFile = file('build.txt')
def buildNum = buildFile.exists() ? buildFile.text.trim().toInteger() : 0
version = "${minecraft_version}-${mod_version}-${buildNum}"

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
}

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true

    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }

        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            workingDirectory project.file('run-data')
            args '--mod', mod_id, '--all', '--output', file('src/data/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

mixin {
    //add sourceSets.main, "${mod_id}.refmap.json"
    //config "${mod_id}.mixins.json"
}

sourceSets.main.scala { srcDir 'src/data/scala' }
sourceSets.main.resources {
    srcDir 'src/data/resources'
    exclude '.cache/**'
}

configurations {
    embedded
    compileClasspath.extendsFrom embedded
    runtimeClasspath.extendsFrom embedded
    implementation.extendsFrom embedded
}

repositories {
    mavenCentral()
    maven {
        name "MightyPirates"
        url "https://maven.cil.li/"
        metadataSources {
            mavenPom()
            artifact()
        }
    }
    maven {
        url "https://maven.squiddev.cc"
        content {
            includeGroup "cc.tweaked"
        }
    }
    maven {
        url "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url "https://modmaven.dev"
        content {
            includeGroup "mezz.jei"
            includeGroup 'appeng'
        }
    }
    maven {
        url "https://chickenbones.net/maven/"
        content {
            includeGroup "codechicken"
            includeGroup "mrtjp"
        }
    }
    maven {
        url "https://modmaven.dev/"
        content {
            includeGroup "appeng"
            includeGroup "mekanism"
        }
    }
    maven {
        url "https://proxy-maven.covers1624.net/"
        content {
            includeModule "net.minecraftforge", "Scorge"
        }
    }
    maven {
        name = "Azure-SLP"
        url = uri("https://pkgs.dev.azure.com/Kotori316/minecraft/_packaging/mods/maven/v1")
        content {
            it.includeModule("com.kotori316", "ScalableCatsForce".toLowerCase())
            it.includeModule("org.typelevel", "cats-core_2.13")
            it.includeModule("org.typelevel", "cats-kernel_2.13")
        }
    }
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        url = "https://maven.createmod.net"
    }
    maven {
        url = "https://maven.ithundxr.dev/mirror"
    }
    flatDir { dirs 'libs' }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    // SLP
    compileOnly(group: 'org.scala-lang', name: 'scala-library', version: "2.13.12")
    compileOnly(group: 'org.typelevel', name: "cats-core_2.13", version: '2.8.1-kotori')
    runtimeOnly(group: "com.kotori316", name: "ScalableCatsForce".toLowerCase(), version: "3.3.1-build-0", classifier: "with-library") {
        transitive(false)
    }

    // OC Libraries
    minecraftLibrary "com.typesafe:config:1.4.5"
    minecraftLibrary ":OC-LuaJ-20220907.1"
    minecraftLibrary ":OC-JNLua-Natives-20220928.1"
    embedded "com.typesafe:config:1.4.5"
    embedded ":OC-LuaJ-20220907.1"
    embedded ":OC-JNLua-Natives-20220928.1"

    def jeiSlug = "jei-${minecraft_version}"

    // TIS-3D
    compileOnly fg.deobf("curse.maven:tis-3d-238603:${tis3d_version}")

    // Jade
    compileOnly fg.deobf("curse.maven:jade-324717:${jade_version}")

    // CC: Tweaked
    compileOnly fg.deobf("cc.tweaked:cc-tweaked-${minecraft_version}-common-api:${cct_version}")
    compileOnly fg.deobf("cc.tweaked:cc-tweaked-${minecraft_version}-core-api:${cct_version}")
    compileOnly fg.deobf("cc.tweaked:cc-tweaked-${minecraft_version}-forge-api:${cct_version}")
    runtimeOnly fg.deobf("cc.tweaked:cc-tweaked-${minecraft_version}-forge:${cct_version}")

    // Modern Fix
    runtimeOnly fg.deobf("maven.modrinth:modernfix:${modernfix_version}")

    // CoFH & Thermal
    compileOnly fg.deobf("curse.maven:cofh-core-69162:4801048")
    compileOnly fg.deobf("curse.maven:thermal-foundation-222880:4788649")

    // Create
    implementation(fg.deobf("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false })
    implementation(fg.deobf("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}"))
    runtimeOnly(fg.deobf("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}"))
    runtimeOnly(fg.deobf("com.tterrag.registrate:Registrate:${registrate_version}"))
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation("io.github.llamalad7:mixinextras-forge:0.4.1")

    // AE2
    compileOnly fg.deobf("appeng:appliedenergistics2-forge:${ae2_version}:api")

    // Mekanism
    compileOnly fg.deobf("mekanism:Mekanism:${mekanism_version}:api")
    runtimeOnly fg.deobf("mekanism:Mekanism:${mekanism_version}")
    runtimeOnly fg.deobf("mekanism:Mekanism:${mekanism_version}:generators")

    // JEI
    runtimeOnly fg.deobf("mezz.jei:${jeiSlug}-forge:${jei_version}")
    compileOnly fg.deobf("mezz.jei:${jeiSlug}-forge-api:${jei_version}")

    // CodeChicken
    compileOnly fg.deobf("curse.maven:cb-multipart-258426:5292585")
    compileOnly fg.deobf("curse.maven:codechicken-lib-1-8-242818:5753868")

    // EnderStorage
    compileOnly fg.deobf("curse.maven:ender-storage-1-8-245174:5292573")

    // Project: Red
    compileOnly fg.deobf("mrtjp:ProjectRed:${projred_version}:core")

    testImplementation "org.scala-lang:scala-library:2.13.12"
    testImplementation "org.scalatest:scalatest_3:3.2.18"
    testImplementation "org.scalatestplus:junit-4-13_3:3.2.18.0"
    testImplementation "junit:junit:4.13.2"

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = mod_group_id
            artifactId = mod_id
            version = project.version
        }
    }

    repositories {
        maven {
            name = "akkiserver"
            url = "https://maven.akkiserver.uk/releases/"
            credentials {
                username = findProperty("maven_user")
                password = findProperty("maven_password")
            }
        }
    }
}

afterEvaluate {
    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifact(provider {
                    tasks.named("jar").get().outputs.files.singleFile
                }) {
                    builtBy tasks.named("reobfJar")
                    classifier = null
                    extension = "jar"
                }
                artifact(tasks.named("apiJar")) {
                    classifier = 'api'
                    extension = "jar"
                }
                artifact(tasks.named("apiSourcesJar")) {
                    classifier = 'sources'
                    extension = "jar"
                }
            }
        }
    }
}

tasks.register('updateBuildNumber') {
    mustRunAfter 'clean'
    doLast {
        def f = file('build.txt')
        if (!f.exists()) f.text = '0'
        def next = f.text.trim().toInteger() + 1
        f.text = next.toString()
        project.version = "${minecraft_version}-${mod_version}-${next}"
    }
}

tasks.named('build') {
    dependsOn updateBuildNumber
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [minecraft_version   : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             forge_version       : forge_version,
                             forge_version_range: forge_version_range,
                             loader_version_range: loader_version_range,
                             mod_id              : mod_id,
                             mod_name: mod_name,
                             mod_license: mod_license,
                             mod_version: mod_version,
                             mod_authors         : mod_authors,
                             mod_description: mod_description,
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes(["Specification-Title"     : mod_id,
                    "Specification-Vendor"    : mod_authors,
                    "Specification-Version"   : "1",
                    "Implementation-Title"    : project.name,
                    "Implementation-Version"  : project.jar.archiveVersion,
                    "Implementation-Vendor"   : mod_authors,
                    "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")])
    }

    from({
        configurations.embedded.collect { it.isDirectory() ? it : zipTree(it) }
    }) {
        exclude 'META-INF', 'META-INF/**'
    }

    finalizedBy 'reobfJar'
}

tasks.register('apiJar', Jar) {
    archiveClassifier = 'api'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from sourceSets.main.output
    include 'li/cil/oc/api/**'
}

tasks.register('apiSourcesJar', Jar) {
    archiveClassifier = 'sources'
    from sourceSets.main.allJava
    include 'li/cil/oc/api/**'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.withType(ScalaCompile).configureEach {
    scalaCompileOptions.forkOptions.memoryMaximumSize = '2g'
    scalaCompileOptions.forkOptions.jvmArgs = ['-Xss4m']
}