org.gradle.daemon=false
org.gradle.jvmargs=-Xmx3G --add-opens java.base/sun.reflect.annotation=ALL-UNNAMED
org.gradle.configureondemand=false
# Minecraft & Forge Settings
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.4.20
forge_version_range=[47.4.10,)
# scala is 2.13.12
loader_version_range=[3.3.1-build-0]
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
#mapping_channel=official
#mapping_version=1.20.1

# Mod Information
mod_id=opencomputers
mod_name=OpenComputers
mod_group_id=li.cil.oc
mod_version=1.9.1-snapshot
mod_authors=MightyPirates
mod_description=Computers.
mod_license=MIT

# External Dependencies
ae2_version=15.4.10
cct_version=1.119.0
jade_version=6855440
jei_version=15.20.0.129
mekanism_version=1.20.1-10.4.16.80
modernfix_version=5.26.2+mc1.20.1
tis3d_version=5266276
projred_version=1.20.1-4.21.0
ccl_version=1.20.1-4.4.0.516
cbmultipart_version=1.20.1-3.3.0.146
casm_version=2.0.1.14
enderstorage_version=1.20.1-2.11.0.188
create_version=6.0.8-291
ponder_version=1.0.92
flywheel_version=1.0.6-278
registrate_version=MC1.20-1.3.3
# Publishing
curse_project_id=223008
modrinth_project_id=YiAbZis2