modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT and CC0; see META-INF/LICENSE and META-INF/licenses"
issueTrackerURL="https://github.com/PC-Logix/OpenComputers/issues"

[[mods]]
modId="opencomputers"
entryClass="li.cil.oc.OpenComputers"
version="${mod_version}"
displayName="OpenComputers: Rebooted"
displayURL="https://github.com/PC-Logix/OpenComputers"
logoFile="pack.png"
credits="Inspired by a couple of other mods, most notably ComputerCraft."
authors="Sangar, Vexatos, payonel, magik6k, Lord Joda, Github Contributors; 1.20.1 port by akki697222; 1.21.1+ port by OpenComputers: Rebooted Team"
description="This mod adds modular computers and robots that can be programmed in Lua."
enumExtensions="META-INF/enumextensions.json"

[[mixins]]
config="opencomputers.mixins.json"

[[mixins]]
config="opencomputers.core.mixins.json"

[[dependencies.opencomputers]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.opencomputers]]
    modId="sable"
    type="optional"
    versionRange="${sable_version_range}"
    ordering="AFTER"
    side="BOTH"
